-- GENERATED by scripts/build-catchup-sql.mjs — do not edit by hand.
--
-- Migrations 0116_payment_plans.sql through 0141_payment_payer.sql, in order, in one
-- paste. Safe to run more than once: every statement is guarded, so the
-- ones already applied do nothing rather than failing and rolling back the
-- ones that are not.

-- ===========================================================================
-- 0116_payment_plans.sql
-- ===========================================================================
-- Taking money: one-off, in instalments, or on a subscription.
--
-- And, first, fixing the thing that stopped any of it reconciling. Invoicing
-- called Stripe's customers.create every single time, so one contact of ours
-- ended up as five or six customers of Stripe's. Nothing could be tied back
-- to a person, which is exactly what "reconcile payments with our contacts"
-- means.

-- ---------------------------------------------------------------------------
-- One contact, one Stripe customer
-- ---------------------------------------------------------------------------
alter table customers add column if not exists stripe_customer_id text;

comment on column customers.stripe_customer_id is
  'This contact in Stripe. Found or created once and reused — a second customer for the same person is a payment that reconciles to nobody.';

create unique index if not exists customers_stripe_id_idx
  on customers(stripe_customer_id) where stripe_customer_id is not null;

-- ---------------------------------------------------------------------------
-- The plan somebody agreed to
-- ---------------------------------------------------------------------------
create table if not exists payment_plans (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  job_id uuid references jobs(id) on delete cascade,
  proposal_id uuid references job_proposals(id) on delete set null,
  customer_id uuid not null references customers(id) on delete cascade,

  kind text not null check (kind in ('one_time', 'instalments', 'subscription')),

  -- Whole cents, always. A total in dollars is a float, and a float is how a
  -- customer ends up a penny short of paid off forever.
  total_cents bigint not null check (total_cents > 0),
  deposit_cents bigint not null default 0 check (deposit_cents >= 0),
  instalments int check (instalments is null or instalments between 1 and 60),
  interval text check (interval in ('weekly', 'monthly', 'quarterly', 'yearly')),

  -- offered  — sent to the customer, not yet agreed
  -- accepted — they said yes; the schedule below is now owed
  -- active   — money has started arriving
  -- settled  — paid off
  -- cancelled
  status text not null default 'offered'
    check (status in ('offered', 'accepted', 'active', 'settled', 'cancelled')),

  accepted_at timestamptz,
  -- Who accepted. A client accepting from a link has no account, so this is
  -- null for them and set when somebody in the office does it for them.
  accepted_by uuid references profiles(id),

  stripe_subscription_id text unique,

  created_by uuid references profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists payment_plans_job_idx on payment_plans(job_id);
create index if not exists payment_plans_customer_idx on payment_plans(customer_id, created_at desc);
create index if not exists payment_plans_org_idx on payment_plans(organization_id, status);

alter table payment_plans enable row level security;
drop policy if exists "org_scoped_payment_plans" on payment_plans;
create policy "org_scoped_payment_plans" on payment_plans for all to authenticated
  using (organization_id = current_org_id())
  with check (organization_id = current_org_id());

-- ---------------------------------------------------------------------------
-- The payments the plan is made of
-- ---------------------------------------------------------------------------
-- Written out at acceptance rather than worked out on the fly. What somebody
-- agreed to pay is a fact about a moment, and a schedule recomputed from a
-- total that later changed is a schedule nobody agreed to.
create table if not exists payment_plan_instalments (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references payment_plans(id) on delete cascade,

  number int not null check (number > 0),
  amount_cents bigint not null check (amount_cents > 0),
  due_on date not null,
  is_deposit boolean not null default false,

  status text not null default 'due'
    check (status in ('due', 'paid', 'failed', 'cancelled')),

  stripe_invoice_id text unique,
  stripe_payment_intent_id text,
  hosted_url text,
  paid_at timestamptz,

  created_at timestamptz not null default now(),

  unique (plan_id, number)
);

create index if not exists payment_plan_instalments_plan_idx
  on payment_plan_instalments(plan_id, number);
-- What is due and unpaid, which is the only query the chasing screen makes.
create index if not exists payment_plan_instalments_due_idx
  on payment_plan_instalments(due_on) where status = 'due';

alter table payment_plan_instalments enable row level security;
drop policy if exists "org_scoped_plan_instalments" on payment_plan_instalments;
create policy "org_scoped_plan_instalments" on payment_plan_instalments for all to authenticated
  using (
    exists (
      select 1 from payment_plans p
      where p.id = payment_plan_instalments.plan_id and p.organization_id = current_org_id()
    )
  )
  with check (
    exists (
      select 1 from payment_plans p
      where p.id = payment_plan_instalments.plan_id and p.organization_id = current_org_id()
    )
  );

-- ---------------------------------------------------------------------------
-- Money that actually arrived
-- ---------------------------------------------------------------------------
-- Every payment, against the contact it came from. This is the reconciliation:
-- Stripe tells us a customer paid, and because a contact now has exactly one
-- Stripe customer, that resolves to a person rather than to an id.
create table if not exists payments (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  customer_id uuid references customers(id) on delete set null,
  job_id uuid references jobs(id) on delete set null,
  plan_id uuid references payment_plans(id) on delete set null,
  instalment_id uuid references payment_plan_instalments(id) on delete set null,

  amount_cents bigint not null,
  currency text not null default 'usd',

  -- 'card' through Stripe, or cash and cheque somebody logged by hand.
  method text not null default 'card' check (method in ('card', 'cash', 'check', 'other')),

  -- Unique so a webhook delivered twice records one payment. Stripe retries
  -- on any non-2xx, and a duplicate payment row is a customer who appears to
  -- have paid twice.
  stripe_payment_intent_id text unique,
  stripe_invoice_id text,

  received_at timestamptz not null default now(),
  note text,
  recorded_by uuid references profiles(id),
  created_at timestamptz not null default now()
);

create index if not exists payments_customer_idx on payments(customer_id, received_at desc);
create index if not exists payments_job_idx on payments(job_id);
create index if not exists payments_org_idx on payments(organization_id, received_at desc);

alter table payments enable row level security;
drop policy if exists "org_scoped_payments" on payments;
create policy "org_scoped_payments" on payments for all to authenticated
  using (organization_id = current_org_id())
  with check (organization_id = current_org_id());

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0117_payment_invoice_ref.sql
-- ===========================================================================
-- The invoice a payment came from, whoever raised it.
--
-- Payments already carry stripe_invoice_id, and that column means exactly
-- what it says: an `in_...` id belonging to a Stripe invoice. The money this
-- business has actually taken was invoiced somewhere else — the charges carry
-- a GoHighLevel invoice id in their metadata — and putting one of those in a
-- column named for Stripe would be a lie that reads like a fact. The webhook
-- matches instalments on stripe_invoice_id; a foreign id sitting in it is a
-- match waiting to happen against the wrong row.
--
-- So: a second column that says what it is. Which invoice, in whatever system
-- raised it. Grouping reads both.

alter table payments add column if not exists source_invoice_ref text;

comment on column payments.source_invoice_ref is
  'The invoice this payment settled, in whichever system raised it (GoHighLevel, a paper book, Stripe). Not a Stripe id — that is stripe_invoice_id. Two payments sharing this are one piece of work.';

-- The only query this column exists for: gather the payments that settled one
-- invoice. Partial, because most rows have nothing to gather.
create index if not exists payments_source_invoice_idx
  on payments(source_invoice_ref) where source_invoice_ref is not null;

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0118_proposal_objections.sql
-- ===========================================================================
-- What clients ask before they say yes, and what happened next.
--
-- A proposal that goes quiet tells you nothing. A proposal where somebody
-- tapped "the price is more than I expected", read the answer, and then asked
-- to drop the back fence tells you what the objection was, whether the stock
-- answer worked, and what it cost to win the job. That is the difference
-- between guessing at a close rate and knowing where quotes actually stall.
--
-- Every row is a thing a client did at a moment. None of it is derived, and
-- none of it gets edited afterwards.

create table if not exists proposal_objections (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  proposal_id uuid not null references job_proposals(id) on delete cascade,

  -- The catalogue id ('price_high', 'cannot_pay_at_once'…), or 'other' when
  -- the client had something we had no answer for. Deliberately text and not
  -- a foreign key: the catalogue lives in code, and a row recording what
  -- somebody asked in March should survive us rewording the question in May.
  objection_id text not null,

  -- Free text, and only reachable once a stock answer has been read and
  -- rejected. A row with this set is the queue of objections we cannot yet
  -- handle — which is the list worth reading every month.
  note text,

  -- What we offered, and what they took: 'explain', 'payment_plan',
  -- 'reduce_scope', 'talk', or null when they only read the answer.
  resolution text check (
    resolution is null or resolution in ('explain', 'payment_plan', 'reduce_scope', 'talk')
  ),

  -- Did the stock answer settle it. Null while they are still reading.
  resolved boolean,

  raised_at timestamptz not null default now()
);

create index if not exists proposal_objections_proposal_idx
  on proposal_objections(proposal_id, raised_at desc);
-- The month-end question: what are people asking that we have no answer for.
create index if not exists proposal_objections_unresolved_idx
  on proposal_objections(organization_id, raised_at desc) where resolved is false;

alter table proposal_objections enable row level security;
drop policy if exists "org_scoped_proposal_objections" on proposal_objections;
create policy "org_scoped_proposal_objections" on proposal_objections for all to authenticated
  using (organization_id = current_org_id())
  with check (organization_id = current_org_id());

-- ---------------------------------------------------------------------------
-- Asking to keep only part of the work
-- ---------------------------------------------------------------------------
-- Kept apart from the objection that prompted it, because it outlives it: a
-- client can trim the scope without ever having pressed an objection, and the
-- office needs to find the request either way.
--
-- 'applied' means the price re-derived cleanly and the proposal already says
-- the new number. 'needs_review' means it did not — a hand-entered line, a
-- discount, a line with no price — and a person has to answer. The client is
-- told which, because a quote that silently changes is worse than one that
-- takes a day.
create table if not exists proposal_scope_requests (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  proposal_id uuid not null references job_proposals(id) on delete cascade,

  -- Zone names, snapshotted. Not ids: the proposal's scope is itself a
  -- snapshot, and the zones on the live canvas may have been renamed or
  -- deleted since it was sent.
  kept_zones text[] not null default '{}',
  dropped_zones text[] not null default '{}',

  -- Cents. The price before and the price after, so the office can see what
  -- the trim cost without recomputing anything.
  previous_total_cents bigint,
  new_total_cents bigint,

  status text not null default 'needs_review'
    check (status in ('applied', 'needs_review', 'accepted', 'rejected')),
  review_reason text,

  requested_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references profiles(id)
);

create index if not exists proposal_scope_requests_proposal_idx
  on proposal_scope_requests(proposal_id, requested_at desc);
-- The work list: what a person still has to answer.
create index if not exists proposal_scope_requests_open_idx
  on proposal_scope_requests(organization_id, requested_at desc) where status = 'needs_review';

alter table proposal_scope_requests enable row level security;
drop policy if exists "org_scoped_proposal_scope_requests" on proposal_scope_requests;
create policy "org_scoped_proposal_scope_requests" on proposal_scope_requests for all to authenticated
  using (organization_id = current_org_id())
  with check (organization_id = current_org_id());

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0119_early_start_requests.sql
-- ===========================================================================
-- "We're done here — can we start the next one?"
--
-- A crew that finishes at two has three hours of daylight and nothing to do
-- with them. The office finds out tomorrow. Meanwhile the customer booked for
-- Thursday would have taken Tuesday gladly, and nobody asked.
--
-- This is the asking. Deliberately a request and not a start: the account
-- manager owns what the customer is expecting, and a crew arriving two days
-- early unannounced is a complaint, not a favour.

create table if not exists early_start_requests (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,

  job_id uuid not null references jobs(id) on delete cascade,
  -- The visit they want to pull forward. Cascades: a cancelled visit is not a
  -- decision anybody still needs to make.
  session_id uuid not null references job_work_sessions(id) on delete cascade,

  requested_by uuid not null references profiles(id) on delete cascade,
  -- The day they are asking to do it on, which is nearly always today. Stored
  -- rather than inferred from raised_at: somebody asking at half four for
  -- tomorrow morning is a different question from asking to start now.
  requested_for date not null,
  note text,

  status text not null default 'pending' check (status in ('pending', 'approved', 'declined')),
  decided_by uuid references profiles(id),
  decided_at timestamptz,
  decline_reason text,

  created_at timestamptz not null default now()
);

create index if not exists early_start_requests_session_idx
  on early_start_requests(session_id, created_at desc);
-- The account manager's queue.
create index if not exists early_start_requests_open_idx
  on early_start_requests(organization_id, requested_for) where status = 'pending';

-- One open ask per visit. Without this, a crew tapping twice on a slow
-- connection puts two identical questions in front of the account manager,
-- and answering one leaves the other sitting there.
create unique index if not exists early_start_requests_one_open_idx
  on early_start_requests(session_id) where status = 'pending';

alter table early_start_requests enable row level security;
drop policy if exists "org_scoped_early_start_requests" on early_start_requests;
create policy "org_scoped_early_start_requests" on early_start_requests for all to authenticated
  using (organization_id = current_org_id())
  with check (organization_id = current_org_id());

-- A channel of its own, rather than borrowing one.
--
-- Folding this into "walkthrough requests" would mean the settings screen
-- offers a toggle that silently governs something it does not name, and the
-- first person to switch walkthroughs off loses these without being told.
--
-- Defaults on, like walkthroughs and unlike the rest: this is a crew standing
-- in a finished garden waiting for an answer, and it goes stale within hours.
alter table notification_preferences
  add column if not exists schedule_requests boolean not null default true;

comment on column notification_preferences.schedule_requests is
  'Crew asking to pull a booked visit forward. Time-critical: the answer is worthless tomorrow.';

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0120_email_sending.sql
-- ===========================================================================
-- Sending our own email, from domains we prove we own.
--
-- Reputation attaches to the domain that signs the mail. A cold campaign sent
-- from jslandscapingmd.com spends every bounce and every spam report against
-- the same name that carries the invoices and the password resets, and that
-- damage is slow to do and much slower to undo.
--
-- So the root domain sends nothing. Transactional mail goes from one
-- subdomain, marketing from another, and the root is left free to hold a
-- strict DMARC policy — its reputation stays untouchable because it has none
-- to spend. The rule is enforced in the app, not written on a help page,
-- because an advisory version is one somebody skips at nine at night.

create table if not exists email_domains (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,

  -- Always a subdomain. Never the registrable domain itself.
  hostname text not null,
  stream text not null check (stream in ('transactional', 'marketing')),

  -- Who is actually sending it, and their id for this domain, so a status
  -- check does not have to search by name.
  provider text not null default 'resend',
  provider_domain_id text,

  status text not null default 'pending' check (status in ('pending', 'verified', 'failed')),
  -- The DNS the owner still has to add, exactly as the provider gave it. Kept
  -- verbatim: a DKIM value we have "tidied" is a DKIM value that fails, and
  -- the failure arrives as silence rather than an error.
  dns_records jsonb not null default '[]'::jsonb,
  last_checked_at timestamptz,

  created_by uuid references profiles(id),
  created_at timestamptz not null default now(),

  unique (organization_id, hostname)
);

-- One domain per stream. Two marketing domains is two reputations to keep an
-- eye on and no way to say which a campaign went from.
create unique index if not exists email_domains_one_per_stream_idx
  on email_domains(organization_id, stream);

alter table email_domains enable row level security;
drop policy if exists "org_scoped_email_domains" on email_domains;
create policy "org_scoped_email_domains" on email_domains for all to authenticated
  using (organization_id = current_org_id())
  with check (organization_id = current_org_id());

-- ---------------------------------------------------------------------------
-- The addresses themselves
-- ---------------------------------------------------------------------------
-- Added by hand, one at a time, because every one of them is a place a human
-- reply can land and somebody has to be reading it.
create table if not exists email_senders (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  domain_id uuid not null references email_domains(id) on delete cascade,

  -- Stored lower-cased, so two spellings of one address cannot both exist.
  address text not null,
  display_name text,

  -- Where replies actually go. Almost always a real monitored mailbox on the
  -- root domain — the sending subdomain exists to protect reputation, not to
  -- be somewhere anybody reads.
  reply_to text,

  is_default boolean not null default false,
  created_by uuid references profiles(id),
  created_at timestamptz not null default now(),

  unique (organization_id, address)
);

create index if not exists email_senders_domain_idx on email_senders(domain_id);
-- One default per domain, so "which address did that go from" has one answer.
create unique index if not exists email_senders_one_default_idx
  on email_senders(domain_id) where is_default;

alter table email_senders enable row level security;
drop policy if exists "org_scoped_email_senders" on email_senders;
create policy "org_scoped_email_senders" on email_senders for all to authenticated
  using (organization_id = current_org_id())
  with check (organization_id = current_org_id());

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0121_knowledge_issues.sql
-- ===========================================================================
-- Problems on the graph, and what solves them.
--
-- Everything on the knowledge graph so far is a thing the business has or
-- does. There was nowhere to put a thing that is wrong — the trailer gate
-- that does not latch, the route that wastes forty minutes, the material
-- nobody local stocks. Those went in people's heads, which is where problems
-- go to be forgotten and rediscovered.
--
-- An issue is a flag rather than a type, because a problem is always a
-- problem *about* something: a piece of equipment, a process, a supplier. It
-- keeps its own kind, and gets marked as broken on top.

alter table knowledge_nodes add column if not exists is_issue boolean not null default false;

comment on column knowledge_nodes.is_issue is
  'Something that is wrong and needs solving. Drawn red until a solution is linked. Deliberately a flag, not a node_type — a problem is always a problem about something, and that something keeps its own kind.';

-- The work list: every problem nobody has answered yet.
create index if not exists knowledge_nodes_open_issues_idx
  on knowledge_nodes(organization_id) where is_issue;

-- ---------------------------------------------------------------------------
-- A picture of it
-- ---------------------------------------------------------------------------
-- Mostly for issues, where a photo of the bent gate settles in one glance
-- what a paragraph argues about. Available on every node because a photo of
-- the right part number is worth the same.
alter table knowledge_nodes add column if not exists image_path text;

comment on column knowledge_nodes.image_path is
  'A photo in the knowledge-images bucket. On an issue this is usually the fastest description of the problem there is.';

insert into storage.buckets (id, name, public)
values ('knowledge-images', 'knowledge-images', true)
on conflict (id) do nothing;

drop policy if exists "read_knowledge_images" on storage.objects;
create policy "read_knowledge_images"
  on storage.objects for select to authenticated
  using (bucket_id = 'knowledge-images');

drop policy if exists "write_knowledge_images" on storage.objects;
create policy "write_knowledge_images"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'knowledge-images');

drop policy if exists "update_knowledge_images" on storage.objects;
create policy "update_knowledge_images"
  on storage.objects for update to authenticated
  using (bucket_id = 'knowledge-images');

drop policy if exists "delete_knowledge_images" on storage.objects;
create policy "delete_knowledge_images"
  on storage.objects for delete to authenticated
  using (bucket_id = 'knowledge-images');

-- ---------------------------------------------------------------------------
-- What solves it
-- ---------------------------------------------------------------------------
-- A new edge kind rather than reusing 'enables' or 'replaces'. Whether an
-- issue is still open is read off these edges, so the answer has to come from
-- an edge that means only this — 'related_to' between a problem and an idea
-- says somebody was thinking about it, not that they fixed it.
--
-- The constraint is rebuilt rather than added to, because a CHECK holds one
-- list and there is no way to append to it in place. Existing rows all match
-- a value that is still in the list, so nothing is orphaned by this.
alter table knowledge_relationships
  drop constraint if exists knowledge_relationships_relationship_type_check;

alter table knowledge_relationships
  add constraint knowledge_relationships_relationship_type_check
  check (relationship_type in (
    'uses','requires','produces','depends_on','similar_to','shares_resource_with',
    'can_be_combined_with','enables','replaces','leads_to','sold_through',
    'purchased_from','performed_by','used_by','located_at','requires_skill',
    'requires_equipment','requires_material','has_cost','generates_revenue',
    'part_of','parent_of','child_of','related_to','solved_by'
  ));

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0122_service_scope_template.sql
-- ===========================================================================
-- The wording a client reads about a service.
--
-- Every zone on a proposal prints a heading and a paragraph under it. That
-- paragraph came only from the built-in service catalogue compiled into the
-- app, which knows nothing about a service this business invented — so a
-- custom service printed a heading and nothing at all, eight times over on
-- one proposal.
--
-- This is where the business writes its own. Editable per service on the
-- Services screen, and used for built-in services too, so wording anybody
-- disagrees with can be fixed without a deploy.

alter table services add column if not exists scope_template text;

comment on column services.scope_template is
  'What a client is told this service covers. Falls back to the built-in wording when blank, and is itself overridden by anything typed on the individual zone — that was written standing in the garden.';

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0123_service_performed_by.sql
-- ===========================================================================
-- Who actually turns up for a service.
--
-- Not all of it is our own crew. Some work goes to a local business we
-- partner with, and a client is entitled to know which before they agree to
-- let anybody onto their property. The proposal answered "who will be at my
-- property?" with a flat "our own crew, not subcontractors", which is true of
-- most of the work and a lie about the rest.
--
-- Set per service, because that is the level at which it is actually true: we
-- do the mulch and the mowing, somebody else does the tree work.

alter table services add column if not exists performed_by text not null default 'own'
  check (performed_by in ('own', 'partner'));

comment on column services.performed_by is
  'Whether our own crew does this service or a partner business does. Decides what a client is told about who will be on their property.';

-- The partner's trading name, which is the name the client will see on a
-- truck in their driveway and should therefore be the name on the proposal.
alter table services add column if not exists partner_name text;

comment on column services.partner_name is
  'The partner business as the client would see it on their truck. Only meaningful when performed_by is partner.';

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0124_acceptance_payment_path.sql
-- ===========================================================================
-- What the client chose to do about paying, and what that means for booking.
--
-- Accepting used to be the end of the road: the status changed, an invoice
-- for the whole amount went out, and the client was looking at a thank-you.
-- Anybody who wanted to spread the cost had to ring up and ask, so the ones
-- who did not ring simply did not pay.
--
-- Acceptance now leads into the one question left, and the answer decides
-- when the crew gets booked, because those are the same decision.

alter table job_proposals add column if not exists payment_path text
  check (payment_path is null or payment_path in ('full', 'plan', 'plan_no_discount'));

comment on column job_proposals.payment_path is
  'How the client chose to pay after accepting. Null means they have accepted but not yet chosen, which is a job waiting on the client rather than on us.';

alter table job_proposals add column if not exists payment_path_at timestamptz;

-- ---------------------------------------------------------------------------
-- The condition the discount came with
-- ---------------------------------------------------------------------------
-- A discount is a discount for money up front. It survives as long as the
-- balance is cleared before the crew starts, which is why a plan that keeps
-- it books from the final payment rather than from today. Stored on the plan
-- rather than worked out later: it is a term somebody agreed to at a moment,
-- and a rule recomputed from today's settings is a rule nobody agreed to.
alter table payment_plans add column if not exists keeps_discount boolean not null default true;

comment on column payment_plans.keeps_discount is
  'Whether the proposal discount survives this plan. False when the client chose to start sooner and give it up.';

alter table payment_plans add column if not exists schedules_after_final_payment boolean not null default false;

comment on column payment_plans.schedules_after_final_payment is
  'Hold the booking until the balance is cleared. True only where a discount is being protected: a job that starts before the last payment has had the discount without the thing it was for.';

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0125_client_chosen_day.sql
-- ===========================================================================
-- The day the client picked for themselves.
--
-- jobs.project_start_date already holds when work starts, but it is written
-- by the office too, so it cannot answer "did the client choose this". That
-- matters: a day we offered and they accepted is a promise, and a day we
-- moved them to is a conversation we still owe them.
--
-- Kept on the proposal rather than the job because it belongs to the same
-- moment as accepting and choosing how to pay, and because a job that is
-- rescheduled later should not overwrite what the client originally asked
-- for.

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_name = 'job_proposals' and column_name = 'client_chosen_day'
  ) then
    alter table job_proposals add column client_chosen_day date;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_name = 'job_proposals' and column_name = 'client_chosen_day_at'
  ) then
    alter table job_proposals add column client_chosen_day_at timestamptz;
  end if;

  -- What we charged them, so a Stripe session that came back paid can be
  -- matched to the proposal it settled without guessing at amounts.
  if not exists (
    select 1 from information_schema.columns
    where table_name = 'job_proposals' and column_name = 'checkout_session_id'
  ) then
    alter table job_proposals add column checkout_session_id text;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_name = 'job_proposals' and column_name = 'paid_at'
  ) then
    alter table job_proposals add column paid_at timestamptz;
  end if;
end $$;

comment on column job_proposals.client_chosen_day is
  'The work day the client picked themselves from the days we offered.';
comment on column job_proposals.checkout_session_id is
  'Stripe Checkout session raised when they chose how to pay.';

-- ===========================================================================
-- 0126_proposal_views.sql
-- ===========================================================================
-- Whether the client has actually opened their proposal.
--
-- "Sent" and "read" are different facts and the office only had the first
-- one. A proposal nobody has opened needs a nudge; one opened six times in
-- two days needs a phone call, not a nudge. Without this, both look
-- identical from the inside.
--
-- A row per view rather than a counter on the proposal, so the count, the
-- first open and the last open all come from the same place and cannot drift
-- apart. Counters also lose the shape of it: six opens in an hour is a
-- household deciding, six opens across three weeks is somebody stalling.

create table if not exists proposal_views (
  id uuid primary key default gen_random_uuid(),
  proposal_id uuid not null references job_proposals(id) on delete cascade,

  viewed_at timestamptz not null default now(),

  -- Who, roughly, without keeping anything about them. A hash of the address
  -- and browser salted with the proposal's own id, so it separates the client
  -- from their spouse on the same page and cannot be lined up against the
  -- same person's visit to any other proposal.
  visitor_hash text,

  created_at timestamptz not null default now()
);

-- The only query this table has: one proposal's views, newest first.
create index if not exists proposal_views_proposal_idx
  on proposal_views(proposal_id, viewed_at desc);

-- Repeat visits inside the dedupe window are found by this before writing.
create index if not exists proposal_views_visitor_idx
  on proposal_views(proposal_id, visitor_hash, viewed_at desc);

alter table proposal_views enable row level security;

-- Readable by the office, scoped through the proposal it belongs to. Nothing
-- here is written by a signed-in user: the client has no account, so the
-- insert goes through the service role like the rest of the public proposal
-- path.
drop policy if exists "org_scoped_proposal_views" on proposal_views;
create policy "org_scoped_proposal_views" on proposal_views for all to authenticated
  using (
    exists (
      select 1 from job_proposals p
      where p.id = proposal_views.proposal_id and p.organization_id = current_org_id()
    )
  )
  with check (
    exists (
      select 1 from job_proposals p
      where p.id = proposal_views.proposal_id and p.organization_id = current_org_id()
    )
  );

comment on table proposal_views is
  'One row per time a client opened their proposal. Internal only — never shown on the public page.';

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0127_flyer_bookings.sql
-- ===========================================================================
-- Selling a flyer spot to somebody outside the business.
--
-- flyer_ad_spots already holds what is on the current flyer, filled in by
-- hand by whoever took the call. This is the other half: a run somebody can
-- buy into from a link, without a phone call and without anybody here typing
-- their details in afterwards.
--
-- Two tables because a run and a booking are different lifetimes. A run is
-- printed once and then it is history; a booking belongs to one run and to
-- one advertiser, and both of those want to be looked up later.

create table if not exists flyer_runs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,

  name text not null,
  -- The day it goes to the post office. Null while it is still being filled.
  mails_on date,

  -- Stored rather than read from the code, because a run printed last spring
  -- at a different price is a fact about last spring. A constant would
  -- quietly rewrite history the first time the price changes.
  flyer_count int not null default 2500 check (flyer_count > 0),
  spot_price_cents bigint not null default 30000 check (spot_price_cents >= 0),

  -- open    — taking bookings, this is the one the public link sells
  -- closed  — full or cut off, artwork is with the printer
  -- printed — done
  status text not null default 'open' check (status in ('open', 'closed', 'printed')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists flyer_runs_org_idx on flyer_runs(organization_id, status);

alter table flyer_runs enable row level security;
drop policy if exists "org_scoped_flyer_runs" on flyer_runs;
create policy "org_scoped_flyer_runs" on flyer_runs for all to authenticated
  using (organization_id = current_org_id())
  with check (organization_id = current_org_id());

-- ---------------------------------------------------------------------------
-- One advertiser, one spot, one run
-- ---------------------------------------------------------------------------
create table if not exists flyer_bookings (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  run_id uuid not null references flyer_runs(id) on delete cascade,

  business_name text not null,
  contact_name text,
  email text,
  phone text,

  -- Their artwork in the flyer-ads bucket. Null until they upload.
  image_path text,

  -- draft    — filling the form in, nothing owed
  -- approved — they have seen the preview and said yes, payment not taken
  -- paid     — money in, the spot is theirs
  -- placed   — assigned a slot on the printed sheet
  -- refunded
  status text not null default 'draft'
    check (status in ('draft', 'approved', 'paid', 'placed', 'refunded')),

  -- Which tile on the sheet, once it is theirs. Null until paid: holding a
  -- slot for somebody who has not paid is how a run sells six spots and
  -- prints four.
  slot int check (slot is null or slot between 1 and 8),

  amount_cents bigint check (amount_cents is null or amount_cents >= 0),
  checkout_session_id text,
  paid_at timestamptz,

  -- Their own link back to this booking, so they can return to a half
  -- finished one without an account.
  token text not null unique,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists flyer_bookings_run_idx on flyer_bookings(run_id, status);
create index if not exists flyer_bookings_org_idx on flyer_bookings(organization_id, created_at desc);

-- One advert per tile per run. Two adverts in one square is not a flyer, it
-- is a mistake somebody finds after 2,500 are printed.
create unique index if not exists flyer_bookings_slot_idx
  on flyer_bookings(run_id, slot) where slot is not null;

alter table flyer_bookings enable row level security;
drop policy if exists "org_scoped_flyer_bookings" on flyer_bookings;
create policy "org_scoped_flyer_bookings" on flyer_bookings for all to authenticated
  using (organization_id = current_org_id())
  with check (organization_id = current_org_id());

comment on table flyer_bookings is
  'An outside business buying a tile on one flyer run, from the public link.';

-- Advertisers upload their own artwork with no account, so the bucket has to
-- take an anonymous write. It is already public to read.
drop policy if exists "public_write_flyer_ads" on storage.objects;
create policy "public_write_flyer_ads"
  on storage.objects for insert
  to anon
  with check (bucket_id = 'flyer-ads');

drop policy if exists "public_read_flyer_ads" on storage.objects;
create policy "public_read_flyer_ads"
  on storage.objects for select
  to anon
  using (bucket_id = 'flyer-ads');

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0128_business_contact_type.sql
-- ===========================================================================
-- Local businesses we approach about the flyer.
--
-- They are not clients, leads, suppliers or subcontractors. They are the
-- other side of the advertising: somebody we ring to sell a tile to. Filing
-- them as "other" put them in the unsorted pile with everything nobody had
-- decided about, which is where a call list goes to die.

alter table customers drop constraint if exists customers_contact_type_check;

alter table customers add constraint customers_contact_type_check
  check (contact_type in (
    'client',
    'lead',
    'supplier',
    'subcontractor',
    'referral_partner',
    'business',
    'other'
  ));

comment on column customers.contact_type is
  'What kind of contact this is. business = a local business we approach about advertising on the flyer.';

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0129_flyer_artwork_kind.sql
-- ===========================================================================
-- Whether the advertiser sent a finished advert or a reference.
--
-- Most local businesses do not have a print-ready 4 by 4.75 at 300 DPI. They
-- have a photo of last year's newspaper ad and a logo somewhere. Refusing
-- those loses the sale; taking them without recording which is which is how
-- somebody's holiday snap ends up on 2,500 flyers.

alter table flyer_bookings add column if not exists artwork_kind text
  not null default 'ready'
  check (artwork_kind in ('ready', 'reference'));

comment on column flyer_bookings.artwork_kind is
  'ready = print it as sent. reference = they want us to design the advert from this.';

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0130_flyer_upload_limit.sql
-- ===========================================================================
-- A size ceiling on advertiser artwork.
--
-- The file used to travel through a Server Action, which capped it at a
-- megabyte by accident and broke every photo taken on a phone. It goes
-- straight to storage now, so the ceiling has to be set where the file
-- actually lands rather than left to a limit nobody chose.
--
-- 25MB: a 300 DPI print file at this size is a few megabytes, and a phone
-- photograph is rarely more than eight.

update storage.buckets
set file_size_limit = 26214400,
    allowed_mime_types = array['image/png', 'image/jpeg', 'application/pdf']
where id = 'flyer-ads';

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0131_proposal_edits.sql
-- ===========================================================================
-- What the office took off a proposal after it went out.
--
-- A client rings and says the back bed is out of budget. The proposal is
-- trimmed in place, on the same token, so their existing link shows the
-- shorter version — and that is exactly why this table exists. Without it,
-- the only record of what was dropped is the difference between a snapshot
-- we overwrote and one nobody kept, which is to say no record at all.
--
-- Deliberately append-only in practice: one row per trim, holding what came
-- off and what the price did, so "why is this five hundred cheaper than the
-- quote I remember" has an answer with a name and a date on it.

create table if not exists proposal_edits (
  id uuid primary key default gen_random_uuid(),
  proposal_id uuid not null references job_proposals(id) on delete cascade,
  organization_id uuid not null references organizations(id),
  -- Who did it. Null only if the profile is later deleted.
  edited_by uuid references profiles(id) on delete set null,
  edited_by_name text,
  -- [{ zoneName, serviceLabel, priceCents }, ...]
  removed_zones jsonb not null default '[]',
  -- [{ zoneName, line }, ...]
  removed_lines jsonb not null default '[]',
  previous_total_cents integer,
  new_total_cents integer,
  -- Why, in the office's own words. Optional; the removals usually say it.
  note text,
  created_at timestamptz not null default now()
);

create index if not exists proposal_edits_proposal_idx on proposal_edits (proposal_id, created_at desc);

alter table proposal_edits enable row level security;
drop policy if exists "org_scoped_proposal_edits" on proposal_edits;
create policy "org_scoped_proposal_edits" on proposal_edits for all to authenticated
  using (organization_id = current_org_id())
  with check (organization_id = current_org_id());

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0132_conversation_reads.sql
-- ===========================================================================
-- Two things the inbox could not say.
--
-- 1. Whether anybody has dealt with a message. "Needs a reply" was worked out
--    from who spoke last, which is right until somebody rings the client back
--    instead of typing. The conversation then sits at the top of the list
--    forever, and a list that lies about what is outstanding gets ignored.
--
--    One row per job and channel, holding how far the office has read. Team
--    wide rather than per person on purpose: a client waiting on an answer is
--    waiting on the business, not on whoever happened to open the app.
--
-- 2. What a client's message is about. A message sent from a proposal used to
--    arrive as a bare sentence, so "can we skip that one?" reached somebody
--    with no idea which area they meant. The reference is snapshotted at send
--    time, because it describes what they were looking at, which is not
--    something a later edit should rewrite.

create table if not exists conversation_reads (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references jobs(id) on delete cascade,
  channel text not null,
  organization_id uuid not null references organizations(id),
  -- Everything up to and including this moment has been dealt with.
  read_through timestamptz not null default now(),
  read_by uuid references profiles(id) on delete set null,
  read_by_name text,
  updated_at timestamptz not null default now(),
  unique (job_id, channel)
);

alter table conversation_reads enable row level security;
drop policy if exists "org_scoped_conversation_reads" on conversation_reads;
create policy "org_scoped_conversation_reads" on conversation_reads for all to authenticated
  using (organization_id = current_org_id())
  with check (organization_id = current_org_id());

-- What the client was looking at when they wrote. Null on everything the
-- office sends and on anything written outside a proposal.
alter table job_messages add column if not exists reference_label text;
alter table job_messages add column if not exists reference_kind text;

comment on column job_messages.reference_label is
  'What this message is about, snapshotted when it was sent — an area of the proposal, or the proposal itself.';

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0133_proposal_edit_source.sql
-- ===========================================================================
-- Where a change to a proposal came from.
--
-- Most of them arrive as a text message. The client reads the proposal on
-- their phone, does not use the buttons on it, and texts "can we leave the
-- back bed for now" instead. Somebody in the office then makes the change,
-- and the record said only that the office made it — which reads, months
-- later, like we quietly took work off a quote nobody asked us to change.
--
-- So a trim records who asked for it and how they asked, alongside the note
-- of what they actually said.

alter table proposal_edits add column if not exists requested_via text;

comment on column proposal_edits.requested_via is
  'How the client asked for this change: text, call, in_person, or office when it was our own decision.';

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0134_evaluation_edits.sql
-- ===========================================================================
-- Changes made to an evaluation after the walk.
--
-- The evaluation is captured on the site map, which is right for the walk
-- and wrong for everything afterwards. A client texts "the back bed is more
-- like thirty foot" and somebody in the office changes the number. Without a
-- record, the measurement simply differs from what was measured on the day,
-- with nothing saying who changed it or why — and the price follows the
-- measurement.
--
-- One row per save, holding the list of changes in the words somebody would
-- use out loud, so it reads as a record rather than two snapshots to diff.

create table if not exists evaluation_edits (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references jobs(id) on delete cascade,
  organization_id uuid not null references organizations(id),
  edited_by uuid references profiles(id) on delete set null,
  edited_by_name text,
  -- ["Back bed measurement 20 × 10 ft → 30 × 10 ft", "Removed Front bed"]
  changes jsonb not null default '[]',
  -- How the client asked: text, call, in_person, or office for our own call.
  requested_via text,
  -- What they actually said, in their words.
  note text,
  created_at timestamptz not null default now()
);

create index if not exists evaluation_edits_job_idx on evaluation_edits (job_id, created_at desc);

alter table evaluation_edits enable row level security;
drop policy if exists "org_scoped_evaluation_edits" on evaluation_edits;
create policy "org_scoped_evaluation_edits" on evaluation_edits for all to authenticated
  using (organization_id = current_org_id())
  with check (organization_id = current_org_id());

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0135_pipeline_override.sql
-- ===========================================================================
-- Moving a job on the board by hand.
--
-- The stage is derived from what is already true — the job's status, its
-- evaluation, its proposal — and that is right nearly always. Nearly. A
-- client says yes on the phone and the proposal is still sitting at "sent";
-- an evaluation happened but nobody pressed the button; work started early as
-- a favour. In those the board is wrong and there is nothing to correct it
-- with, because the thing that would correct it is the paperwork that has not
-- caught up.
--
-- So a job can be placed by hand. What is stored is not the stage on its own
-- but the stage *and the derived answer it was overriding* — so the moment
-- the underlying facts move, the override is known to be about a situation
-- that no longer exists and the automatic answer takes back over. An override
-- that outlives its reason is the stored-status problem all over again.

alter table jobs add column if not exists pipeline_override_stage text;
alter table jobs add column if not exists pipeline_override_status text;
-- The derived status at the moment somebody moved it. The staleness check.
alter table jobs add column if not exists pipeline_override_from text;
alter table jobs add column if not exists pipeline_override_at timestamptz;
alter table jobs add column if not exists pipeline_override_by uuid references profiles(id) on delete set null;
alter table jobs add column if not exists pipeline_override_note text;

comment on column jobs.pipeline_override_from is
  'What the pipeline would have said when the job was moved by hand. When the derived answer stops matching this, the move is about a situation that has passed and the automatic position wins again.';

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0136_contact_import_conflict_target.sql
-- ===========================================================================
-- The index the contact import upserts onto.
--
-- Re-importing a CRM export has to update the people it already knows rather
-- than add second copies of them, and the honest way to say that is one
-- statement per few hundred rows that inserts or updates on the CRM's own id.
-- Postgres will only resolve that against an index it can infer from the
-- conflict target, and it refuses to infer a *partial* index unless the
-- statement repeats the index's condition word for word — which PostgREST,
-- which is what the app actually speaks to, has no way to express.
--
-- So the same uniqueness is stated as a plain index. Nothing about what is
-- allowed changes: a unique index never considers two nulls equal, so rows
-- with no external id were never constrained by the partial one either, and
-- the "where external_id is not null" it carried only ever saved space.
--
-- Without this, an import that means to update falls back to inserting, which
-- is how a contact book ends up with everybody in it twice.

create unique index if not exists customers_org_external_id_key
  on customers(organization_id, external_id);

-- Redundant the moment the index above exists, and an index maintained on
-- every write for nothing is a cost paid forever.
drop index if exists customers_external_id_idx;

comment on index customers_org_external_id_key is
  'One contact per CRM id per organisation. Named as the conflict target by the contact import, which is why it is a plain index rather than a partial one.';

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0137_job_disputes.sql
-- ===========================================================================
-- Jobs that have gone wrong.
--
-- The board reads a job's position off what is true about it: booked, quoted,
-- sold, being built. None of that has an answer for a client threatening to
-- sue, or refusing to pay. Those jobs sat in Operations looking like work to
-- get on with, which is exactly what nobody should do with them.
--
-- Deliberately not a job status. A dispute is something that happened to a
-- job which already had a position, and when it is resolved the job goes back
-- to being read normally rather than needing to be put back by hand.
--
-- Resolving records a date rather than clearing the row. The history is the
-- point: whoever quotes this client next should be able to find out that the
-- last job ended with a solicitor's letter.

alter table jobs add column if not exists dispute_opened_at timestamptz;
alter table jobs add column if not exists dispute_resolved_at timestamptz;
-- legal, payment, quality or other.
alter table jobs add column if not exists dispute_kind text;
alter table jobs add column if not exists dispute_reason text;
alter table jobs add column if not exists dispute_opened_by uuid references profiles(id) on delete set null;

comment on column jobs.dispute_opened_at is
  'When this job went into dispute. A job is in dispute while this is set and later than dispute_resolved_at, which is how a second dispute reopens one that was closed.';
comment on column jobs.dispute_reason is
  'What is wrong, in the office''s own words. Shown on the pipeline card so the board says it without anybody opening the job.';

-- The board reads this constantly; the column is null on nearly every row.
create index if not exists jobs_in_dispute_idx on jobs (dispute_opened_at)
  where dispute_opened_at is not null;

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0138_archived_proposals.sql
-- ===========================================================================
-- The proposals that were written before this app existed.
--
-- Years of quotes live in the old CRM as PDFs. Carrying them across is worth
-- doing for two reasons, and the second is the bigger one. A client's record
-- should say what we have already quoted them, so nobody re-quotes a job we
-- lost on price last spring without knowing. And the ones we did not win are
-- a list: every one is somebody who wanted the work, got a number, and said
-- no or said nothing.
--
-- Deliberately not job_proposals. Those are generated from a site map, carry
-- a scope snapshot and a token a client can open, and every one of them is
-- live paperwork. These are documents about work that is already over. Trying
-- to make one table serve both would mean a job_proposals row with no job, no
-- scope and no token, which is three lies to store one PDF.

create table if not exists archived_proposals (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id),
  customer_id uuid not null references customers(id) on delete cascade,
  -- Where the PDF sits in the proposal-archive bucket.
  file_path text not null,
  file_name text not null,
  -- won, lost or disputed. What actually happened, which is the whole reason
  -- to carry these over rather than leave them in the old system.
  outcome text not null check (outcome in ('won', 'lost', 'disputed')),
  -- When the work was done, or was going to be. Not when the file was made:
  -- a quote written in March for an April job belongs in April.
  job_date date,
  -- What the job was, in a few words, so a list of eleven PDFs is readable.
  title text,
  amount numeric,
  notes text,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists archived_proposals_customer_idx
  on archived_proposals (customer_id, job_date desc);
-- The list phase two works from: everything we quoted and did not win.
create index if not exists archived_proposals_outcome_idx
  on archived_proposals (organization_id, outcome);

alter table archived_proposals enable row level security;
drop policy if exists "org_scoped_archived_proposals" on archived_proposals;
create policy "org_scoped_archived_proposals" on archived_proposals for all to authenticated
  using (organization_id = current_org_id())
  with check (organization_id = current_org_id());

-- Private, unlike the image buckets. These carry a client's name, address and
-- what they were charged, and a public bucket is a public URL away from being
-- a filing cabinet anybody can read. Signed links only, and only for someone
-- signed in.
insert into storage.buckets (id, name, public)
values ('proposal-archive', 'proposal-archive', false)
on conflict (id) do nothing;

drop policy if exists "team_read_proposal_archive" on storage.objects;
create policy "team_read_proposal_archive"
  on storage.objects for select to authenticated
  using (bucket_id = 'proposal-archive');

drop policy if exists "team_write_proposal_archive" on storage.objects;
create policy "team_write_proposal_archive"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'proposal-archive');

drop policy if exists "team_delete_proposal_archive" on storage.objects;
create policy "team_delete_proposal_archive"
  on storage.objects for delete to authenticated
  using (bucket_id = 'proposal-archive');

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0139_payment_import.sql
-- ===========================================================================
-- Payments brought in from wherever the money was actually taken.
--
-- The payments table already holds what this needs. What it lacked was a
-- stable key from the exporting system, so running the same file twice paid
-- everybody twice.
--
-- A plain unique index rather than a partial one, for the reason 0136 spells
-- out: Postgres will not infer a partial index as an ON CONFLICT target
-- unless the statement repeats the predicate, and PostgREST cannot send one.
-- A unique index never treats two nulls as equal, so rows with no external id
-- -- every payment somebody typed in by hand -- are unaffected.

alter table payments add column if not exists external_id text;
alter table payments add column if not exists source text;

create unique index if not exists payments_org_external_id_key
  on payments(organization_id, external_id);

comment on column payments.external_id is
  'The exporting system''s own transaction id. The conflict target the payment import upserts on, so re-running a file updates rather than duplicates.';
comment on column payments.source is
  'Where this came from: an import name, or null for one recorded in the app.';

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0140_processing_fees.sql
-- ===========================================================================
-- Card fees, and a stable key for anything imported into the ledger.
--
-- The payments import records what a client paid. What it could not record is
-- what the processor took on the way through: five thousand four hundred
-- pounds of card fees across one year's transactions, which is the difference
-- between money received and money kept. Without it every profit figure in
-- the app is high by that amount, and quietly.
--
-- Fees belong in the ledger as an expense rather than being netted off the
-- payment. What the client paid is what the client paid; the fee is something
-- the business spent to take it, and burying it inside the receipt is how it
-- stops being visible.
--
-- The external id is the same idea as on payments: an import has to be
-- re-runnable, and a ledger that gains a second copy of every fee each time
-- somebody presses the button is worse than one with no fees in it.

alter table ledger_entries add column if not exists external_id text;

create unique index if not exists ledger_entries_org_external_id_key
  on ledger_entries(organization_id, external_id);

comment on column ledger_entries.external_id is
  'Stable key for an imported entry, so re-running an import updates rather than duplicating. Null on anything typed in by hand.';

-- 'processing_fees' is new. The constraint has to be rebuilt to admit it,
-- and is rebuilt in full rather than patched so it stays readable.
alter table ledger_entries drop constraint if exists ledger_entries_direction_category;
alter table ledger_entries drop constraint if exists ledger_entries_category_check;

alter table ledger_entries
  add constraint ledger_entries_direction_category check (
    (direction = 'in' and category in ('job_payment', 'deposit', 'other_income'))
    or (
      direction = 'out'
      and category in (
        'materials', 'subcontractor', 'fuel', 'equipment', 'permit',
        'processing_fees', 'other_expense'
      )
    )
  );

notify pgrst, 'reload schema';

-- ===========================================================================
-- 0141_payment_payer.sql
-- ===========================================================================
-- Who the payment said it was from.
--
-- An imported payment that could not be matched to a contact used to keep
-- nothing about the payer: the row landed with a null customer and the name
-- and email that came with it were thrown away. So the money sat on a screen
-- as "no contact" with no way to work out whose it was short of finding the
-- original export and running it again.
--
-- The file always knew. It carried a name, usually an email, often a phone,
-- and those are exactly what is needed to find the person or make them. Kept
-- on the row, an orphaned payment can be reconciled at any point afterwards
-- by somebody who never sees the CSV.

alter table payments add column if not exists payer_name text;
alter table payments add column if not exists payer_email text;
alter table payments add column if not exists payer_phone text;

comment on column payments.payer_email is
  'What the payment export said the payer''s email was. Kept so a payment with no contact can be matched up later without the original file.';

-- The lookup behind "match these up": every payment with no contact on it.
create index if not exists payments_unmatched_idx
  on payments (organization_id) where customer_id is null;

notify pgrst, 'reload schema';

notify pgrst, 'reload schema';
